Re #311: cherry-pick 7c4e392 commit, resolve conflicts with #302
-----

btle: report error details from bluepy-helper

In previus commit c1d8c3e74e13101f345a03eef4eae6e327418dd5
bluepy-helper binary gained ability to report detailed error codes
and messages in the 'emsg' and 'estat' response fields.

Propagate these optional fields to the BTLEException class,
and display them (when the exception is converted to a string).

The updated exception string looks like:

   bluepy.btle.BTLEException: Disconnect Error: Failed to execute mgmt cmd \
          'unpair' (estat: 6 emsg: Not Paired)